# Generated by Django 3.0.2 on 2020-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
