# Generated by Django 3.0.2 on 2020-01-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo_bot', '0002_auto_20200129_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viberuser',
            old_name='vibe_id',
            new_name='viber_id',
        ),
    ]
