# Generated by Django 3.0.3 on 2020-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_bot', '0003_auto_20200129_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
