# Generated by Django 3.0.3 on 2020-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_bot', '0004_viberuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='viberuser',
            name='device_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='viberuser',
            name='primary_device_os',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='viberuser',
            name='viber_version',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
